sidebar_categories:
  null:
    - index # What these docs are.
    - why-apollo
    - getting-started # prereqs, step 1, 2, 3, what next
    - whats-new
  Essentials:
    - essentials/building-schema # types, resolvers, "What you need for an executable schema"
    - essentials/queries
    - essentials/mutations
  Schema Development:
    - schemas/types
    - schemas/resolvers
    - schemas/context
    - schemas/organizing-code
  Running a Server:
    - server/index
    - server/middleware
    - server/queries
    - server/engine
    - server/secrets
  Best Practices:
    - best-practices/infrastructure # possibly includes deployment
    - best-practices/authentication
    - best-practices/schema-design
    - best-practices/subscriptions
    - best-practices/performance
    - best-practices/caching
    - best-practices/monitoring
    - best-practices/versioning
    - best-practices/schema-stitching
    # - best-practices/deploying maybe in the infra section above (the deploy name is nice)
  Working with Backends:
    - backends/general
    - backends/sql
    - backends/mongodb
    - backends/rest
    - backends/prisma
  API Reference:
    - api/apollo-server
    - api/graphql-subscriptions
    - api/apollo-engine